### ISSUE TITLE
"Archive" data instead of deleting

### ISSUE THREAD

**Issue by autoreleasefool** [autoreleasefool/approach#352]
Deleting is too ruthless. Accidental deletions can cause users to lose a lot of data. By "archiving" instead, we can exclude data from stats, but give a recovery method.

**Comment by jbrains** [comment]
It's not clear that archiving is an intentional choice to those of us who actually want to delete accidentally-added games. I'm not sure how to make that nicer in the UI, but I would prefer not to have figured out what to do by reading this issue. 😉

**Comment by jbrains** [comment]
Oops. Even worse. Archiving did nothing for me on Android.
