### ISSUE TITLE
Scoring when 10th frame final ball no score

### ISSUE THREAD

**Issue by drlambert100** [autoreleasefool/approach#552]
I have found that if, in the tenth frame, there are no pins knocked down with the final ball, the score won't calculate. You have to remove the remaining or one of the remaining pins and replace it before the score will calculate for the game. Unless, there is a trick that I'm not aware of to get the score without advancing to the next game and then returning to the previous game to find the final score.

**Comment by autoreleasefool** [comment]
Fixed in da44c3378, release will come later this week

**Comment by drlambert100** [comment]
Thanks for keeping me in the loop.

***@***.***
